import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

import { useEffect } from 'react'
import Router from 'next/router'

import useUser from 'app/data/use-user'
import { logout } from 'app/lib/auth'

import { useDispatch } from 'react-redux'
import { setUserData } from 'app/store/slices/auth'

const Home: NextPage = () => {
  const dispatch = useDispatch()
  const { user, loading, loggedOut, mutate } = useUser()

  // if logged out, redirect to the homepage
  useEffect(() => {
    if (loggedOut) {
      Router.replace('/login')
    }
    if (user) {
      dispatch(setUserData(user))
    }
  }, [loggedOut, user, dispatch])
  if (loggedOut) return <h1>Redirecting...</h1>
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {loading || !user ? (
          <h1>Loading...</h1>
        ) : (
          <>
            <h1>Welcome, {user?.firstName}</h1>
            <p>This is your dashboard.</p>
            <button
              onClick={() => {
                logout()
                mutate()
                Router.replace('/login')
              }}
            >
              Logout
            </button>
          </>
        )}
      </main>
    </div>
  )
}

export default Home
